name: CD

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Set Playwright browsers path
        run: |
          echo "PLAYWRIGHT_BROWSERS_PATH=0" >> $GITHUB_ENV

      - name: Install Playwright Chromium
        run: |
          python -m playwright install chromium

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Upload release asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main
          tag_name: ${{ github.event.inputs.tag }} || ${{ github.event.release.tag_name }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}